services:

  laravel-crm:
    container_name: laravel-crm
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8010:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-crm
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8011:80
    environment:
      - PMA_ARBITRARY=1