services:

  crm:
    container_name: crm-l8
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8080:80
    
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm-l8
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1